name = "silent-room"
main = "src/index.ts"
compatibility_date = "2026-04-01"
workers_dev = true   # 禁用 workers.dev 域名
preview_urls = true  # 禁用预览 URL

[vars]
TURNSTILE_SECRET_KEY = ""
CLEAR_HISTORY_DAYS = 3
MAX_UPLOAD_SIZE = 200
SITE_TITLE = "Technology Chat"
SITE_DESCRIPTION = "安全加密的即时通讯应用"
SITE_FAVICON = "/logo.svg"
SITE_LOGO = "/logo.svg"
SITE_VERSION = "2.0.1"
ALLOWED_DOMAINS = "https://www.vmoweopl.freeddns.org,https://technology-chat.pages.dev,https://flue-chat.pages.dev,https://www.mooning-room.accesscam.org,http://localhost:5173,https://flue-chat.vniwaejivos.workers.dev"
PASSWORD_SALT = "dIP0aAoi5wrhOcIQoB4UOglx5nkCsyOGDmXPeNI7"
ENVIRONMENT = "dev"


[[d1_databases]]
binding = "DB"
database_name = "silent-room"
database_id = "055aacab-c30a-4622-9d42-a90622dd303d"

[[kv_namespaces]]
binding = "UPLOADS"
id = "34aa41a27a874d919d1cef2ca5e4e1d8"

[[r2_buckets]]
binding = "R2"
bucket_name = "lumen-chat-files"

[[durable_objects.bindings]]
name = "CHAT"
class_name = "ChatRoom"

[triggers]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]
